-- CampusBoard database
create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) >= 4),
  body text not null check (char_length(body) >= 10),
  category text not null,
  author text not null,
  likes integer not null default 0 check (likes >= 0),
  created_at timestamptz not null default now()
);

alter table public.notices enable row level security;

create policy "Anyone can read notices" on public.notices for select using (true);
create policy "Anyone can create notices" on public.notices for insert with check (true);
create policy "Anyone can update notices" on public.notices for update using (true) with check (true);
create policy "Anyone can delete notices" on public.notices for delete using (true);

insert into public.notices (title, body, category, author, likes) values
('Freshers Welcome Night','Join us Friday at 6 PM in the main auditorium. Games, music and free snacks for everyone.','Events','Student Council',24),
('Library Hours Extended','The central library will stay open until midnight during the upcoming assessment period.','Academic','Library Team',18),
('Football Team Trials','Trials are open to all students this Wednesday at the sports ground. Bring your student ID.','Sports','Sports Club',31);
